# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: src/x_r1/test/MVOT/exp_sft/dataset
num_processes: 2

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: output/Qwen2.5-1.5B-MVOT
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: False
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger: true
use_liger_kernel: true
warmup_ratio: 0.05

#lora_r: 32
#lora_target_modules: ["q_proj","v_proj", "k_proj", "embed_tokens"]
#lora_alpha: 8
#lora_dropout: 0.0
#bias: "none"
#use_peft: true
