# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  4x3090(24G)/4090(24G)
# running time 2~3h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: src/cv_extraction/XR1-750/raw
dataset_configs:
- train
num_processes: 2

# reward config
trainer_type: "GRPOTrainer"
reward_funcs: ['accuracy', 'thinking', 'format']
#reward_funcs: ['accuracy', 'thinking', 'accuracy_thinking', 'format']
reward_weights: [1.0, 0.6, 1.0]
#reward_weights: [1.0, 0.0, 1.0]
#reward_weights: [0.0, 0.0, 1.0, 1.0]
# part_of_gradient: True
part_of_gradient: False
reward_type: "num"

# vllm config
vllm_mode: colocate
vllm_tensor_parallel_size: 2
temperature: 0.7
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.8
max_prompt_length: 512
max_completion_length: 1024

# eval config
do_eval: True
eval_strategy: "steps"
eval_steps: 40

# gradient checkpoint and lr
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-06
warmup_ratio: 0.1
lr_scheduler_type: cosine

# GRPO
gradient_accumulation_steps: 4
num_generations: 6
num_iterations: 4 
num_train_epochs: 1
per_device_eval_batch_size: 3
per_device_train_batch_size: 3

# saving
output_dir: output/test-0.5B
push_to_hub: False
save_strategy: "epoch"
overwrite_output_dir: true

# logging
report_to:
- wandb
log_completions: true
log_level: info
logging_steps: 1
logging_strategy: steps
seed: 42

# liger kernel
use_liger: true
use_liger_kernel: true