# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >= 1x3090(24G)
#
# running time ~8h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: src/cv_extraction/XR1-7500/exp
dataset_configs:
- train
num_processes: 2

# GRPO trainer config
trainer_type: "XGRPOTrainer"
reward_funcs: ['accuracy', 'thinking', 'format']
reward_weights: [1.0, 0.6, 1.0]
part_of_gradient: True
regex: True
temperature: 0.6
quick_eval_dataset: src/cv_extraction/MATH-500/exp
bf16: true
use_vllm: True
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: false
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
num_generations: 2
num_iterations: 2
max_completion_length: 1024
max_steps: -1
num_train_epochs: 3
output_dir: output/X-R1-test
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
push_to_hub: False
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1
use_liger_kernel: true

# lora config
# task_type: model_args.lora_task_type
# lora_in_4bit: True # no support QLoRA
#lora_r: 32
#lora_target_modules: ["q_proj","v_proj", "k_proj", "embed_tokens"]
#lora_alpha: 8
#lora_dropout: 0.0
#bias: "none"
#use_peft: true
