# This is X-R1(https://github.com/dhcode-cpp/X-R1) project training config:
# required >=  4x3090(24G)/4090(24G)
# running time ~1h

# Model arguments
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
reference_model: Qwen/Qwen2.5-7B-Instruct

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-750
dataset_configs:
- train
num_processes: 2

# GRPO trainer config
trainer_type: "XGRPOSupervisedTrainer"
temperature: 1.0
# quick_eval_dataset: Maxwell-Jia/AIME_2024
quick_eval_dataset: HuggingFaceH4/MATH-500
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.5
do_eval: no
eval_strategy: "no"
eval_steps: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 3.0e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 256
num_generations: 12
max_completion_length: 1024
max_steps: -1
num_train_epochs: 3
output_dir: output/X-R1-0.5B-supervsiedby-7B
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 6
push_to_hub: False
report_to:
- wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1
trainer_type: "XGRPOSupervisedTrainer"